wandb_version: 1

architecture:
  desc: null
  value: GCN
learning_rate:
  desc: null
  value: 1.0e-05
hidden_channels:
  desc: null
  value: 32
num_layers:
  desc: null
  value: 3
dropout:
  desc: null
  value: 0.2
epochs:
  desc: null
  value: 1200
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1709493547.467489
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 2
      - 16
      - 23
      4: 3.11.7
      5: 0.16.3
      8:
      - 1
      - 5
      13: darwin-x86_64
